#!/usr/bin/env python3


def meme_case(my_string):
    for i, char in enumerate(my_string):
        if i % 2:
            yield char.upper()
        else:
            yield char.lower()


def main():
    my_string = input()
    print(''.join(meme_case(my_string)))


if __name__ == '__main__':
    main()
