#!/bin/sh
sock="/tmp/sad-sock"

song=$(echo playlist | socat UNIX:"$sock" - | \
	grep -v '^OK$' | grep -v '^ERR ' | \
	rofi -dmenu -p "music" )
if test x"$song" != x""; then
	id=$(printf '%s' "$song" | cut -d ':' -f 1)
	printf 'play %s\n' "$id" | socat UNIX:"$sock" -
fi
